#!/bin/bash

PROPERTIES=""
PROPERTIES="$PROPERTIES -Denvironment=PRODUCTION"
PROPERTIES="$PROPERTIES -DmachineId=PRODUCTION-01"
PROPERTIES="$PROPERTIES -DloggingDir=/var/log/server/"
PROPERTIES="$PROPERTIES -DlogLevel=INFO"
PROPERTIES="$PROPERTIES -Dhost=0.0.0.0"
PROPERTIES="$PROPERTIES -Dport=8080"
PROPERTIES="$PROPERTIES -DenableSwagger=false"

exec java $PROPERTIES -jar server.jar
